version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: logserver_clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=logs
      - CLICKHOUSE_USER=default
      # 生产环境请修改为强密码
      - CLICKHOUSE_PASSWORD=clickhouse_2024_secure
      # 设置时区为上海时区
      - TZ=Asia/Shanghai
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - ./init-clickhouse.sql:/docker-entrypoint-initdb.d/init.sql
      # 挂载主机时区文件（双重保障）
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8123/ping",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - logserver-network

  logserver:
    build: .
    container_name: logserver-service
    restart: unless-stopped
    ports:
      - "${PORT:-13000}:13000"
    depends_on:
      clickhouse:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # ClickHouse连接配置
      - CLICKHOUSE_HOST=logserver_clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_DATABASE=logs
      - CLICKHOUSE_USERNAME=default
      # 密码需要与ClickHouse服务保持一致
      - CLICKHOUSE_PASSWORD=clickhouse_2024_secure
      # 设置时区为上海时区
      - TZ=Asia/Shanghai
    volumes:
      # 挂载主机时区文件
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:13000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - logserver-network

networks:
  logserver-network:
    driver: bridge

volumes:
  clickhouse_data:
    driver: local
  clickhouse_logs:
    driver: local
